## Next game Stat Predictions ##

In [827]:
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsRegressor

mvp_train = df_final.loc[50:].copy()
mvp_test = df_final.loc[:51].copy()
results3 = []

for i in range(50):
    X_train = mvp_train[["MIN", "FGM", "FG_PCT", "FGA", "FTA", "FTM"]]
    x_new = mvp_test.loc[i, ["MIN","FGM", "FG_PCT", "FGA", "FTA", "FTM"]]
    scaler = StandardScaler()
    X_train_st = scaler.fit_transform(X_train)
    X_new_st = scaler.transform(pd.DataFrame([x_new])) # needs to be a DataFrame
    y_train = mvp_train["PTS"]
    model = KNeighborsRegressor(n_neighbors=5)
    model.fit(X=X_train_st, y=y_train)
    results3.append(model.predict(X=X_new_st))

Trained most of the data, while use the first 50 as the test data for predictions. The training columns used becuase they are the stats that usually results in a made point in basketball.

In [828]:
df_results3 = pd.DataFrame(data = results2, columns = ['Predicted Pts'])
df_results3["PTS"] = df_final_dpy['PTS'].head(50)
df_results3

    Predicted Pts  PTS
0             3.8    4
1            14.6   14
2            16.2   16
3            26.8   27
4            16.6   16
5            15.2   15
6            21.4   20
7            13.4   13
8            15.0   13
9             8.2    7
10           15.8   15
11            7.8    6
12           13.6   13
13           11.0   11
14           21.4   21
15           12.6   13
16           10.8   10
17           11.2   11
18           12.6   10
19           16.0   16
20           14.2   12
21           15.4   15
22           18.0   18
23           11.6   11
24           16.8   16
25           16.4   17
26           31.2   32
27           19.0   18
28           15.2   13
29           15.6   14
30           10.0   10
31           16.6   15
32           11.0   10
33           20.6   20
34           23.6   24
35           16.6   16
36           22.0   22
37           21.6   21
38           19.4   19
39            6.6    6
40           16.8   16
41           10.0    8
42           12.0   12
43           16.8   16
44           19.2   19
45           24.8   26
46           20.8   21
47            6.2    6
48           17.8   17
49           10.4    8

In [837]:
dpy_train = df_final_dpy.loc[50:].copy()
dpy_test = df_final_dpy.loc[:51].copy()
results = []

for i in range(50):
    X_train = dpy_train[["OREB","DREB"]]
    x_new = dpy_test.loc[i, ["OREB","DREB"]]
    scaler = StandardScaler()
    X_train_st = scaler.fit_transform(X_train)
    X_new_st = scaler.transform(pd.DataFrame([x_new])) # needs to be a DataFrame
    y_train = dpy_train["REB"]
    model = KNeighborsRegressor(n_neighbors=5)
    model.fit(X=X_train_st, y=y_train)
    results.append(model.predict(X=X_new_st))

In [838]:
df_results = pd.DataFrame(data = results, columns = ['Predicted Rebounds'])
df_results["REB"] = df_final_dpy['REB'].head(50)
df_results

    Predicted Rebounds   REB
0                  6.0   6.0
1                 10.0  10.0
2                  7.0   7.0
3                 15.0  15.0
4                  6.0   6.0
5                 12.0  12.0
6                  8.0   8.0
7                 11.6  12.0
8                  8.0   8.0
9                 13.0  13.0
10                12.0  12.0
11                11.0  11.0
12                 7.0   7.0
13                12.0  12.0
14                 8.0   8.0
15                10.0  10.0
16                13.0  13.0
17                 6.0   6.0
18                 8.0   8.0
19                 8.0   8.0
20                 5.0   5.0
21                 8.0   8.0
22                 9.0   9.0
23                 6.0   6.0
24                 8.0   8.0
25                 4.0   4.0
26                 7.0   7.0
27                12.0  12.0
28                 6.0   6.0
29                 5.0   5.0
30                 9.0   9.0
31                 6.0   6.0
32                11.0  11.0
33                 6.0   6.0
34                 2.0   2.0
35                 6.0   6.0
36                 4.0   4.0
37                 5.0   5.0
38                17.0  17.0
39                 3.0   3.0
40                 8.0   8.0
41                 7.0   7.0
42                 1.0   1.0
43                 2.0   2.0
44                 4.0   4.0
45                 5.0   5.0
46                 9.0   9.0
47                 6.0   6.0
48                 4.0   4.0
49                 8.0   8.0

In [1]:
rok_train = df_final_roy.loc[50:].copy()
rok_test = df_final_roy.loc[:51].copy()
results2 = []

for i in range(50):
    X_train = rok_train[["MIN", "FGM", "FG_PCT", "FGA", "FTA", "FTM"]]
    x_new = rok_test.loc[i, ["MIN", "FGM", "FG_PCT", "FGA", "FTA", "FTM"]]
    scaler = StandardScaler()
    X_train_st = scaler.fit_transform(X_train)
    X_new_st = scaler.transform(pd.DataFrame([x_new])) # needs to be a DataFrame
    y_train = rok_train["PTS"]
    model = KNeighborsRegressor(n_neighbors=10)
    model.fit(X=X_train_st, y=y_train)
    results2.append(model.predict(X=X_new_st))

NameError: name 'df_final_roy' is not defined

In [836]:
df_results2 = pd.DataFrame(data = results2, columns = ['Predicted Pts'])
df_results2["PTS"] = df_final_dpy['PTS'].head(50)
df_results2

    Predicted Pts  PTS
0             3.8    4
1            14.6   14
2            16.2   16
3            26.8   27
4            16.6   16
5            15.2   15
6            21.4   20
7            13.4   13
8            15.0   13
9             8.2    7
10           15.8   15
11            7.8    6
12           13.6   13
13           11.0   11
14           21.4   21
15           12.6   13
16           10.8   10
17           11.2   11
18           12.6   10
19           16.0   16
20           14.2   12
21           15.4   15
22           18.0   18
23           11.6   11
24           16.8   16
25           16.4   17
26           31.2   32
27           19.0   18
28           15.2   13
29           15.6   14
30           10.0   10
31           16.6   15
32           11.0   10
33           20.6   20
34           23.6   24
35           16.6   16
36           22.0   22
37           21.6   21
38           19.4   19
39            6.6    6
40           16.8   16
41           10.0    8
42           12.0   12
43           16.8   16
44           19.2   19
45           24.8   26
46           20.8   21
47            6.2    6
48           17.8   17
49           10.4    8

<span style="font-size:2em;">Position Predictor</span>

I chose to filter out data after 1979 because the 3 point line was first introduced in 1980

Some players have primary and secondary position designations i.e SG-SF. We only want to extract the primary position of the player. I decided to extract the first two characters of the Pos column because 4 of the 5 positions(PG, SG,SF,PF). For players with a center(C), if they have a secondary designation, my method extracts the string "C-". This was quickly remedied by replacing "C-" with C

Breaking big dataframe into smaller dataframes by year

In [42]:
position3_df['Year'] = position3_df['Year'].astype(float)

In [43]:
position3_df

,Unnamed: 0,Year,Player,Pos,Age,Tm,G,GS,MP,PER,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
5727,5727,1980.0,Kareem Abdul-Jabbar*,C,32.0,LAL,82.0,NaN,3143.0,25.3,...,0.765,190.0,696.0,886.0,371.0,81.0,280.0,297.0,216.0,2034.0
5728,5728,1980.0,Tom Abernethy,PF,25.0,GSW,67.0,NaN,1222.0,11.0,...,0.683,62.0,129.0,191.0,87.0,35.0,12.0,39.0,118.0,362.0
5729,5729,1980.0,Alvan Adams,C,25.0,PHO,75.0,NaN,2168.0,19.2,...,0.797,158.0,451.0,609.0,322.0,108.0,55.0,218.0,237.0,1118.0
5730,5730,1980.0,Tiny Archibald*,PG,31.0,BOS,80.0,80.0,2864.0,15.3,...,0.830,59.0,138.0,197.0,671.0,106.0,10.0,242.0,218.0,1131.0
5731,5731,1980.0,Dennis Awtrey,C,31.0,CHI,26.0,NaN,560.0,7.4,...,0.640,29.0,86.0,115.0,40.0,12.0,15.0,27.0,66.0,86.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24686,24686,2017.0,Cody Zeller,PF,24.0,CHO,62.0,58.0,1725.0,16.7,...,0.679,135.0,270.0,405.0,99.0,62.0,58.0,65.0,189.0,639.0
24687,24687,2017.0,Tyler Zeller,C,27.0,BOS,51.0,5.0,525.0,13.0,...,0.564,43.0,81.0,124.0,42.0,7.0,21.0,20.0,61.0,178.0
24688,24688,2017.0,Stephen Zimmerman,C,20.0,ORL,19.0,0.0,108.0,7.3,...,0.600,11.0,24.0,35.0,4.0,2.0,5.0,3.0,17.0,23.0
24689,24689,2017.0,Paul Zipser,SF,22.0,CHI,44.0,18.0,843.0,6.9,...,0.775,15.0,110.0,125.0,36.0,15.0,16.0,40.0,78.0,240.0
24690,24690,2017.0,Ivica Zubac,C,19.0,LAL,38.0,11.0,609.0,17.0,...,0.653,41.0,118.0,159.0,30.0,14.0,33.0,30.0,66.0,284.0

Mapping positions to numbers for KNN

In [44]:
total_clean_df["Pos"].replace({"PG": 1, "SG": 2, "SF": 3, "PF": 4, "C": 5}, inplace=True)

In [45]:
total_clean_df

,Unnamed: 0,Year,Player,Pos,Age,Tm,G,GS,MP,PER,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,5727,1980.0,Kareem Abdul-Jabbar*,5,32.0,LAL,82.0,NaN,3143.0,25.3,...,0.765,190.0,696.0,886.0,371.0,81.0,280.0,297.0,216.0,2034.0
1,5728,1980.0,Tom Abernethy,4,25.0,GSW,67.0,NaN,1222.0,11.0,...,0.683,62.0,129.0,191.0,87.0,35.0,12.0,39.0,118.0,362.0
2,5729,1980.0,Alvan Adams,5,25.0,PHO,75.0,NaN,2168.0,19.2,...,0.797,158.0,451.0,609.0,322.0,108.0,55.0,218.0,237.0,1118.0
3,5730,1980.0,Tiny Archibald*,1,31.0,BOS,80.0,80.0,2864.0,15.3,...,0.830,59.0,138.0,197.0,671.0,106.0,10.0,242.0,218.0,1131.0
4,5731,1980.0,Dennis Awtrey,5,31.0,CHI,26.0,NaN,560.0,7.4,...,0.640,29.0,86.0,115.0,40.0,12.0,15.0,27.0,66.0,86.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15515,24686,2017.0,Cody Zeller,4,24.0,CHO,62.0,58.0,1725.0,16.7,...,0.679,135.0,270.0,405.0,99.0,62.0,58.0,65.0,189.0,639.0
15516,24687,2017.0,Tyler Zeller,5,27.0,BOS,51.0,5.0,525.0,13.0,...,0.564,43.0,81.0,124.0,42.0,7.0,21.0,20.0,61.0,178.0
15517,24688,2017.0,Stephen Zimmerman,5,20.0,ORL,19.0,0.0,108.0,7.3,...,0.600,11.0,24.0,35.0,4.0,2.0,5.0,3.0,17.0,23.0
15518,24689,2017.0,Paul Zipser,3,22.0,CHI,44.0,18.0,843.0,6.9,...,0.775,15.0,110.0,125.0,36.0,15.0,16.0,40.0,78.0,240.0
15519,24690,2017.0,Ivica Zubac,5,19.0,LAL,38.0,11.0,609.0,17.0,...,0.653,41.0,118.0,159.0,30.0,14.0,33.0,30.0,66.0,284.0

Initially I didn't think that there were NaN numbers in the dataframe but when I ran the

In [46]:
relevant_clean_df = total_clean_df.filter(["Year", "Pos", "FG%", "3PA", "3P%", "FT%", "ORB", "DRB",
                         "TRB", "AST", "STL", "BLK", "PTS"], axis=1)

In [47]:
import numpy as np

relevant_clean_df.isnull().values.any()

True

In [48]:
 
pd.set_option('display.max_rows', 20)    
nulls = relevant_clean_df.apply(lambda x: sum(x.isnull()), axis = 0)
display(nulls)

Year       0
Pos        0
FG%       44
3PA        0
3P%     2568
FT%      416
ORB        0
DRB        0
TRB        0
AST        0
STL        0
BLK        0
PTS        0
dtype: int64

In [49]:
pd.reset_option('display.max_rows')

In [50]:
#Drop 3 point percentage column, drop rows without fg% or ft%. found out that if you don't attempt any of the percentage
#stats then it will be marked as NaN

relevant_clean_df=relevant_clean_df.drop(["3P%"], axis=1)

relevant_clean_df.dropna(subset=["FG%", "FT%"])

,Year,Pos,FG%,3PA,FT%,ORB,DRB,TRB,AST,STL,BLK,PTS
0,1980.0,5,0.604,1.0,0.765,190.0,696.0,886.0,371.0,81.0,280.0,2034.0
1,1980.0,4,0.481,1.0,0.683,62.0,129.0,191.0,87.0,35.0,12.0,362.0
2,1980.0,5,0.531,2.0,0.797,158.0,451.0,609.0,322.0,108.0,55.0,1118.0
3,1980.0,1,0.482,18.0,0.830,59.0,138.0,197.0,671.0,106.0,10.0,1131.0
4,1980.0,5,0.450,0.0,0.640,29.0,86.0,115.0,40.0,12.0,15.0,86.0
...,...,...,...,...,...,...,...,...,...,...,...,...
15515,2017.0,4,0.571,1.0,0.679,135.0,270.0,405.0,99.0,62.0,58.0,639.0
15516,2017.0,5,0.494,1.0,0.564,43.0,81.0,124.0,42.0,7.0,21.0,178.0
15517,2017.0,5,0.323,0.0,0.600,11.0,24.0,35.0,4.0,2.0,5.0,23.0
15518,2017.0,3,0.398,99.0,0.775,15.0,110.0,125.0,36.0,15.0,16.0,240.0
15519,2017.0,5,0.529,3.0,0.653,41.0,118.0,159.0,30.0,14.0,33.0,284.0

In [51]:
relevant_clean_df = relevant_clean_df.dropna(subset=["FG%", "FT%"])

In [52]:
relevant_clean_df.apply(lambda x: sum(x.isnull()), axis = 0)#check how many nulls per column

Year    0
Pos     0
FG%     0
3PA     0
FT%     0
ORB     0
DRB     0
TRB     0
AST     0
STL     0
BLK     0
PTS     0
dtype: int64

In [53]:
relevant_clean_df = relevant_clean_df.set_index("Year")

In [54]:

relevant_clean_df_00s = relevant_clean_df.loc[:2000.0]

Since the data goes up to 2017, I figured that I would use players from the 2018-2019 season to test if our classifier is accurate

In [55]:
relevant_clean_df_00s["Pos"].value_counts()

4    1610
5    1508
3    1490
2    1489
1    1438
Name: Pos, dtype: int64

In [56]:
#training data for 2000's

X_train = relevant_clean_df_00s[["FG%", "3PA", "FT%", "ORB", "DRB",
                         "TRB", "AST", "STL", "BLK", "PTS"]]
x_new = pd.Series()

<ipython-input-56-225e16c72722>:5: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  x_new = pd.Series()

Since the data goes up to 2017, I figured that I would use players from the 2018-2019 season to test if our classifier is accurate

In [57]:
#Allen Iverson 2001-2002

x_new = pd.Series()

x_new["FG%"] = 0.398
x_new["3PA"] = 89.0
x_new["FT%"] = 0.812
x_new["ORB"] = 44.0
x_new["DRB"] = 225.0
x_new["TRB"] = 269.0
x_new["AST"] = 331.0
x_new["STL"] = 168.0
x_new["BLK"] = 13.0
x_new["PTS"] = 1883.0

<ipython-input-57-5ada9433f484>:3: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  x_new = pd.Series()

In [58]:
#Kobe

x_new["FG%"] = 0.459
x_new["3PA"] = 415.0
x_new["FT%"] = 0.840 
x_new["ORB"] = 94.0
x_new["DRB"] = 423.0
x_new["TRB"] = 517.0
x_new["AST"] = 441.0
x_new["STL"] = 151.0
x_new["BLK"] = 40.0
x_new["PTS"] = 2323.0

In [59]:
#Yao Ming 2008-2009


x_new["FG%"] = 0.548
x_new["3PA"] = 1.0
x_new["FT%"] = 0.866 
x_new["ORB"] = 204.0
x_new["DRB"] = 557.0
x_new["TRB"] = 761.0
x_new["AST"] = 137.0
x_new["STL"] = 30.0
x_new["BLK"] = 150.0
x_new["PTS"] = 1514.0

In [60]:
#Dirk 2008-2009

x_new["FG%"] = 0.479
x_new["3PA"] = 170.0
x_new["FT%"] = 0.890 
x_new["ORB"] = 88.0
x_new["DRB"] = 593.0
x_new["TRB"] = 681.0
x_new["AST"] = 197.0
x_new["STL"] = 61.0
x_new["BLK"] = 63.0
x_new["PTS"] = 2094.0

In [61]:
#Shane Battier 2008-2009

x_new["FG%"] = 0.410
x_new["3PA"] = 237.0
x_new["FT%"] = 0.821 
x_new["ORB"] = 52.0
x_new["DRB"] = 233.0
x_new["TRB"] = 285.0
x_new["AST"] = 137.0
x_new["STL"] = 48.0
x_new["BLK"] = 54.0
x_new["PTS"] = 436.0

In [62]:
#Steve Nash 2004-2005

x_new["FG%"] = 0.502
x_new["3PA"] = 218.0
x_new["FT%"] = 0.887 
x_new["ORB"] = 57.0
x_new["DRB"] = 192.0
x_new["TRB"] = 249.0
x_new["AST"] = 861.0
x_new["STL"] = 74.0
x_new["BLK"] = 6.0
x_new["PTS"] = 1165.0

Caveat: Players are asked to play different roles and positions outside of their primary positions. This means that they could accumulate a variety of statistics that strongly pertain to certain roles.

Correctly predicted the primary position of Allen Iverson with a 66% probability


PG: 0.27586207, SG(Correct): 0.65517241, SF: 0.06896552, PF: 0. , C: 0.

Correctly predicted primary position of Kobe Bryant with a 45% probability. 

PG: 0.22988506, SG(Correct): 0.49425287, SF: 0.26436782, PF: 0.01149425, C: 0.

Correctly predicted primary postion of Yao Ming with 69% probability. 

PG: 0., SG: 0. , SF: 0.02298851, PF: 0.32183908, C(Correct): 0.65517241

Correctly predicts position of Dirk Nowitzki with 46% probability.

Note: I'm a little surprised to see the probability of playing SG as a non zero answer since in reality, coaches and fans would never even consider the thought of playing Dirk at SG. I had to take a step back and remember that the classifier is going based on the data we feed in. Dirk has some aspects that would be associated with SG's such as a high PT total, high FT% and a fair amount of 3PA.


PG: 0., SG: 0.03448276, SF: 0.28735632, PF(Correct): 0.4137931 , C: 0.26436782

Correctly predicts position of Shane Battier with 44% probability

PG: 0.03448276, SG: 0.35632184, SF(Correct):0.43678161, PF: 0.16091954, C: 0.01149425

Correctly predicts position of Steve Nash with 97% probability

PG(Correct): 0.96551724, SG: 0.03448276, SF: 0. , PF: 0.  , C: 0.

In [63]:
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neighbors import KNeighborsClassifier

# Standardize the training and test data
scaler = StandardScaler()
X_train_st = scaler.fit_transform(X_train)
X_new_st = scaler.transform(pd.DataFrame([x_new])) # needs to be a DataFrame
y_train = relevant_clean_df_00s["Pos"]

# Fit k-nearest neighbors
model = KNeighborsClassifier(n_neighbors=87)# square root of training data. Conveniently an odd number
model.fit(X=X_train_st, y=y_train)
model.predict(X=X_new_st)

array([1])

In [64]:
model.predict_proba(X=X_new_st)

array([[0.96551724, 0.03448276, 0.        , 0.        , 0.        ]])